#!/usr/bin/env perl
use strict;
use warnings;

use Cronin::Runner;

my $runner = Cronin::Runner->new_with_options;
$runner->run;

__END__

=head1 NAME

cronin - Run cron application

=head1 SYNOPSIS

  # Simple
  cronin -- /path/to/your/script

  # Notify to the mail address if the command is failed
  cronin --email=cronin@example.com -- /path/to/your/script

  # Notify to the ARN if the command is failed
  cronin --sns=arn:aws:sns:... -- /path/to/your/script

  # Notify to the URL if the command is failed
  cronin --http=http://example.com/notify -- /path/to/your/script

=head1 DESCRIPTION

cronin is a command line utility to run cron applications.

=head1 ARGUMENTS

=over 4

=item command

  cronin -- /path/to/your/script --opt1 --opt2

The first non-option argument is used as a command.

=back

=head1 OPTIONS

=over 4

=item --sns[=ARN]

Specifies the Amazon SNS ARN.

=item --http[=URL]

Specifies the URL.

=item --email[=MAILTO]

Specifies the mail address.

=item --stdout

Prints results to STDOUT.

=item --tee

Prints to STDOUT and STDERR like tee(1).

=item --json

Notifies with JSON format. Defaults to false.

=item --force-notify

Notifies even if the command is succeeded. Defaults to false.

=item --encoding

Specifies the command output encoding. Defaults to UTF-8.

=back

=head1 AUTHOR

Jiro Nishiguchi

=head1 LICENSE

This library is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

=head1 SEE ALSO

L<Cronin::Runner>

=cut
